# Dependabot Configuration for AG News Classification
# ====================================================
# Automated dependency updates following:
# - GitHub Dependabot Documentation
# - Security Best Practices
# - Academic Software Maintenance Guidelines
#
# Author: Võ Hải Dũng
# License: MIT

version: 2

updates:
  # Python dependencies - pip ecosystem
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    # Update strategy
    versioning-strategy: "increase"
    # Commit message configuration
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Labels for pull requests
    labels:
      - "dependencies"
      - "python"
      - "automated"
    # Reviewers for automated PRs
    reviewers:
      - "VoHaiDung"
    # Milestone assignment
    milestone: 1
    # Allow specific dependency updates
    # Note: 'allow' entries should only specify dependency patterns
    allow:
      # Allow all production dependencies
      - dependency-name: "numpy"
        dependency-type: "direct"
      - dependency-name: "torch"
        dependency-type: "direct"
      - dependency-name: "transformers"
        dependency-type: "direct"
      - dependency-name: "pyyaml"
        dependency-type: "direct"
      # Allow all patch updates for any dependency
      - dependency-name: "*"
        dependency-type: "all"
    # Ignore specific dependencies or update types
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "transformers"
        update-types: ["version-update:semver-major"]
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]
      # Ignore specific versions if needed
      - dependency-name: "pytest"
        versions: ["8.x", "9.x"]

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    reviewers:
      - "VoHaiDung"
    # Allow all GitHub Actions updates
    allow:
      - dependency-type: "all"
    # Ignore specific actions if needed
    ignore:
      # Example: Ignore major updates for checkout action
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]

  # Docker base image dependencies
  - package-ecosystem: "docker"
    directory: "/deployment/docker"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    reviewers:
      - "VoHaiDung"
    # Allow all Docker updates
    allow:
      - dependency-type: "direct"
    # Ignore CUDA images major updates for stability
    ignore:
      - dependency-name: "nvidia/cuda"
        update-types: ["version-update:semver-major"]
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]

  # NPM dependencies (if frontend exists)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps-npm"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "automated"
    # Security updates only for npm
    allow:
      - dependency-type: "all"
    # Only allow patch updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
