name: agnews-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9                     # stable, compatible with HF & PEFT
  - cudatoolkit=11.7               # GPU support (adjust to your CUDA version)
  - pip                            # use pip within Conda
  # Conda-installed dependencies
  - pytorch>=2.0.0
  - pip:
    # Hugging Face libraries
    - transformers>=4.35.0
    - datasets>=2.13.1
    - evaluate>=0.4.0
    - peft>=0.4.0
    # Core utilities
    - numpy>=1.24.0
    - pandas>=2.0.0
    - tqdm>=4.65.0
    - scikit-learn>=1.2.0
    # Visualization & explainability
    - matplotlib>=3.7.0
    - shap>=0.41.0
    # I/O & demo
    - joblib>=1.2.0
    - gradio>=3.30.0
    - jupyterlab>=4.0.0
