# Project Configuration
# =====================
# Python project metadata
# Author: Võ Hải Dũng

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ag-news-classification"
version = "1.0.0"
description = "AG News Text Classification Framework"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name = "Võ Hải Dũng"}]
keywords = ["nlp", "text-classification", "ag-news"]

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310']

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v"
