# Development Environment Configuration
# AG News Text Classification Framework

environment: development
stage: dev
debug: true
verbose: true

# System settings
system:
  seed: 42
  deterministic: true
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true

# Hardware configuration
hardware:
  device: cuda
  gpu_ids: [0]
  mixed_precision: false
  gradient_checkpointing: false
  memory_fraction: 0.8
  allow_tf32: false  # Disable for deterministic results

# Data settings
data:
  base_dir: ./data
  cache_dir: ./.cache/dev
  use_cached_datasets: true
  max_samples: 10000  # Limit samples for faster iteration
  validation_size: 0.2
  test_size: 0.1
  shuffle: true
  
  # Preprocessing
  preprocessing:
    max_length: 256  # Shorter for dev
    batch_size: 16
    normalize_text: true
    remove_special_chars: false
    lowercase: false
  
  # Augmentation (minimal in dev)
  augmentation:
    enabled: false
    techniques: []

# Model settings
model:
  use_pretrained: true
  cache_pretrained: true
  compile_model: false  # Disable torch.compile in dev
  
  # Model selection for dev
  default_model: distilbert-base-uncased  # Lighter model for dev
  
  # Optimization
  quantization: false
  pruning: false

# Training settings
training:
  num_epochs: 3  # Fewer epochs for dev
  batch_size: 16
  gradient_accumulation_steps: 1
  learning_rate: 5e-5
  warmup_steps: 100
  
  # Optimization
  optimizer: adamw
  scheduler: linear
  max_grad_norm: 1.0
  
  # Checkpointing
  save_strategy: epoch
  save_total_limit: 2
  load_best_model_at_end: true
  
  # Evaluation
  evaluation_strategy: steps
  eval_steps: 100
  logging_steps: 20
  
  # Early stopping
  early_stopping: true
  early_stopping_patience: 3
  early_stopping_threshold: 0.001

# Experiment tracking
tracking:
  use_wandb: false
  use_mlflow: false
  use_tensorboard: true
  use_local_logging: true
  
  log_level: DEBUG
  log_to_file: true
  log_dir: ./outputs/logs/dev
  
  # Metrics
  track_metrics: true
  track_gradients: false
  track_parameters: false
  track_embeddings: false

# API settings
api:
  host: localhost
  port: 8000
  workers: 1
  reload: true
  debug: true
  cors_origins: ["http://localhost:3000", "http://localhost:8080"]
  
  # Rate limiting
  rate_limit: 1000
  timeout: 60

# Security (relaxed for dev)
security:
  enable_auth: false
  enable_https: false
  api_key_required: false
  encrypt_data: false

# Monitoring
monitoring:
  enable_profiling: true
  profile_memory: true
  profile_time: true
  
  # Alerts
  enable_alerts: false
  
  # Dashboard
  dashboard_port: 3000
  auto_open_dashboard: false

# Testing
testing:
  run_tests_on_save: true
  test_coverage_threshold: 70
  run_integration_tests: false
  run_performance_tests: false

# Development tools
dev_tools:
  enable_debugger: true
  enable_hot_reload: true
  enable_code_completion: true
  jupyter_kernel: true
  
  # VSCode integration
  vscode_settings:
    python_path: ./venv/bin/python
    linting_enabled: true
    formatting_on_save: true

# Resource limits
resource_limits:
  max_memory_gb: 8
  max_gpu_memory_gb: 6
  max_cpu_percent: 80
  max_disk_gb: 20

# Paths
paths:
  data_dir: ./data
  models_dir: ./outputs/models/dev
  checkpoints_dir: ./outputs/models/dev/checkpoints
  logs_dir: ./outputs/logs/dev
  cache_dir: ./.cache/dev
  temp_dir: ./.tmp/dev
  
# Feature flags
features:
  enable_experimental: true
  enable_beta_features: true
  enable_debug_endpoints: true
  enable_mock_data: true
  
# Quick start settings
quickstart:
  auto_download_data: true
  auto_setup_environment: true
  sample_size: 1000
  quick_train_epochs: 1
