# Production Environment Configuration
# AG News Text Classification Framework

environment: production
stage: prod
debug: false
verbose: false

# System settings
system:
  seed: 42
  deterministic: false  # Better performance
  num_workers: 16
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true

# Hardware configuration
hardware:
  device: cuda
  gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]  # Multi-GPU
  mixed_precision: true
  gradient_checkpointing: true  # Memory efficiency
  memory_fraction: 0.95
  allow_tf32: true
  
  # Distributed training
  distributed:
    backend: nccl
    init_method: env://
    world_size: 8
    rank: 0

# Data settings
data:
  base_dir: /data/agnews
  cache_dir: /cache/agnews
  use_cached_datasets: true
  max_samples: null
  validation_size: 0.1
  test_size: 0.1
  shuffle: true
  
  # Preprocessing
  preprocessing:
    max_length: 512
    batch_size: 64
    normalize_text: true
    remove_special_chars: false
    lowercase: false
  
  # Augmentation
  augmentation:
    enabled: true
    techniques:
      - synonym_replacement
      - back_translation
      - paraphrase
      - mixup
    augmentation_factor: 2.0

# Model settings
model:
  use_pretrained: true
  cache_pretrained: true
  compile_model: true
  
  # Production model
  default_model: deberta-v3-xlarge
  
  # Ensemble
  ensemble:
    enabled: true
    models:
      - deberta-v3-xlarge
      - roberta-large
      - xlnet-large-cased
    method: weighted_voting
    weights: [0.4, 0.35, 0.25]
  
  # Optimization
  quantization: true
  quantization_bits: 8
  pruning: false
  onnx_export: true

# Training settings (for continuous learning)
training:
  num_epochs: 15
  batch_size: 64
  gradient_accumulation_steps: 4
  learning_rate: 2e-5
  warmup_ratio: 0.1
  
  # Optimization
  optimizer: adamw
  scheduler: cosine_with_restarts
  max_grad_norm: 1.0
  weight_decay: 0.01
  label_smoothing: 0.1
  
  # Mixed precision
  fp16: true
  fp16_backend: auto
  
  # Checkpointing
  save_strategy: best
  save_total_limit: 5
  load_best_model_at_end: true
  metric_for_best_model: f1_macro
  greater_is_better: true
  
  # Evaluation
  evaluation_strategy: steps
  eval_steps: 500
  logging_steps: 100

# Inference settings
inference:
  batch_size: 128
  max_batch_size: 256
  dynamic_batching: true
  batch_timeout_ms: 50
  
  # Model serving
  model_server: torchserve
  num_workers: 8
  response_timeout: 10
  
  # Caching
  enable_prediction_cache: true
  cache_ttl: 3600

# Experiment tracking
tracking:
  use_wandb: true
  use_mlflow: true
  use_tensorboard: false
  use_local_logging: true
  
  log_level: WARNING
  log_to_file: true
  log_dir: /logs/agnews
  
  # Metrics
  track_metrics: true
  track_gradients: false
  track_parameters: false
  track_embeddings: false
  
  # Production monitoring
  track_predictions: true
  track_latency: true
  track_throughput: true

# API settings
api:
  host: 0.0.0.0
  port: 443
  workers: 16
  reload: false
  debug: false
  cors_origins: ["https://api.agnews.ai", "https://app.agnews.ai"]
  
  # Rate limiting
  rate_limit: 1000
  burst_limit: 2000
  timeout: 10
  
  # Load balancing
  load_balancer: nginx
  strategy: least_connections

# Security
security:
  enable_auth: true
  enable_https: true
  api_key_required: true
  encrypt_data: true
  
  # SSL
  ssl_cert_file: /certs/prod.crt
  ssl_key_file: /certs/prod.key
  
  # Authentication
  jwt_secret_key: ${JWT_SECRET_KEY}
  jwt_algorithm: RS256
  token_expire_minutes: 30
  
  # API keys
  api_key_rotation: true
  api_key_expire_days: 90
  
  # WAF
  enable_waf: true
  block_suspicious_requests: true

# Monitoring
monitoring:
  enable_profiling: false
  profile_memory: false
  profile_time: false
  
  # Metrics collection
  collect_system_metrics: true
  collect_gpu_metrics: true
  collect_business_metrics: true
  metrics_port: 9090
  
  # Prometheus
  prometheus:
    enabled: true
    pushgateway: http://prometheus-pushgateway:9091
  
  # Grafana
  grafana:
    enabled: true
    dashboard_id: agnews-prod
  
  # Alerts
  enable_alerts: true
  alert_channels: [pagerduty, email, slack]
  alert_rules:
    - metric: error_rate
      threshold: 0.01
      action: page
    - metric: latency_p99
      threshold: 1000  # ms
      action: alert
    - metric: gpu_memory_usage
      threshold: 0.95
      action: alert

# High Availability
high_availability:
  enabled: true
  replicas: 3
  auto_scaling:
    enabled: true
    min_replicas: 3
    max_replicas: 10
    target_cpu: 70
    target_memory: 80
  
  # Health checks
  health_check:
    interval: 10
    timeout: 5
    unhealthy_threshold: 3
    healthy_threshold: 2

# Backup and Recovery
backup:
  enabled: true
  strategy: incremental
  frequency: daily
  retention_days: 30
  backup_location: s3://agnews-backups/prod
  
  # Disaster recovery
  disaster_recovery:
    enabled: true
    rpo_hours: 1  # Recovery Point Objective
    rto_hours: 4  # Recovery Time Objective

# Database
database:
  type: postgresql
  host: prod-db.agnews.ai
  port: 5432
  name: agnews_prod
  pool_size: 50
  max_overflow: 100
  
  # Read replicas
  read_replicas:
    - host: prod-db-read1.agnews.ai
    - host: prod-db-read2.agnews.ai

# Cache
cache:
  type: redis_cluster
  nodes:
    - prod-cache1.agnews.ai:6379
    - prod-cache2.agnews.ai:6379
    - prod-cache3.agnews.ai:6379
  ttl: 7200
  
  # CDN
  cdn:
    enabled: true
    provider: cloudflare
    cache_static_assets: true

# Message Queue
message_queue:
  type: rabbitmq
  host: prod-mq.agnews.ai
  port: 5672
  prefetch_count: 10

# Resource limits
resource_limits:
  max_memory_gb: 128
  max_gpu_memory_gb: 80
  max_cpu_percent: 95
  max_disk_gb: 1000

# Paths
paths:
  data_dir: /data/agnews
  models_dir: /models/agnews
  checkpoints_dir: /models/agnews/checkpoints
  logs_dir: /logs/agnews
  cache_dir: /cache/agnews
  temp_dir: /tmp/agnews

# Feature flags
features:
  enable_experimental: false
  enable_beta_features: false
  enable_debug_endpoints: false
  enable_mock_data: false
  
  # A/B testing
  ab_testing:
    enabled: true
    experiments:
      - name: new_model_test
        percentage: 10
        variant: deberta-v3-xxlarge

# Compliance
compliance:
  gdpr_compliant: true
  log_retention_days: 90
  data_anonymization: true
  audit_logging: true

# Cost optimization
cost_optimization:
  spot_instances: true
  auto_shutdown_idle: true
  idle_timeout_minutes: 30
  
  # Resource scheduling
  scheduled_scaling:
    - schedule: "0 9 * * 1-5"  # Weekday mornings
      min_replicas: 5
      max_replicas: 15
    - schedule: "0 18 * * 1-5"  # Weekday evenings
      min_replicas: 2
      max_replicas: 5
