# Kubernetes Namespace Configuration for AG News Text Classification
# ================================================================================
# This configuration defines the Kubernetes namespaces for organizing and isolating
# resources across different environments and components of the AG News system.
#
# Namespaces provide:
#   - Resource isolation and organization
#   - Security boundaries
#   - Resource quota management
#   - Network policy enforcement
#
# References:
#   - Kubernetes Namespaces: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
#   - Multi-tenancy Best Practices: https://kubernetes.io/docs/concepts/security/multi-tenancy/
#   - Resource Quotas: https://kubernetes.io/docs/concepts/policy/resource-quotas/
#
# Author: Võ Hải Dũng
# License: MIT

---
# Production namespace
apiVersion: v1
kind: Namespace
metadata:
  name: agnews-production
  labels:
    app: agnews
    environment: production
    monitoring: enabled
    security: high
  annotations:
    description: "Production environment for AG News Text Classification"
    owner: "ML Engineering Team"
    contact: "mlops@agnews.ai"

---
# Staging namespace
apiVersion: v1
kind: Namespace
metadata:
  name: agnews-staging
  labels:
    app: agnews
    environment: staging
    monitoring: enabled
    security: medium
  annotations:
    description: "Staging environment for AG News Text Classification"
    owner: "ML Engineering Team"
    contact: "mlops@agnews.ai"

---
# Development namespace
apiVersion: v1
kind: Namespace
metadata:
  name: agnews-development
  labels:
    app: agnews
    environment: development
    monitoring: optional
    security: low
  annotations:
    description: "Development environment for AG News Text Classification"
    owner: "Development Team"
    contact: "dev@agnews.ai"

---
# Data processing namespace
apiVersion: v1
kind: Namespace
metadata:
  name: agnews-data
  labels:
    app: agnews
    component: data-processing
    monitoring: enabled
  annotations:
    description: "Namespace for data processing and ETL pipelines"
    owner: "Data Engineering Team"
    contact: "data@agnews.ai"

---
# Monitoring namespace
apiVersion: v1
kind: Namespace
metadata:
  name: agnews-monitoring
  labels:
    app: agnews
    component: monitoring
    prometheus: enabled
    grafana: enabled
  annotations:
    description: "Monitoring and observability stack"
    owner: "Platform Team"
    contact: "platform@agnews.ai"

---
# Resource Quota for Production namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: agnews-production
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
    services.nodeports: "0"  # Disabled for security

---
# Resource Quota for Staging namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: agnews-staging
spec:
  hard:
    requests.cpu: "50"
    requests.memory: "100Gi"
    limits.cpu: "100"
    limits.memory: "200Gi"
    persistentvolumeclaims: "5"
    services.loadbalancers: "1"
    services.nodeports: "0"

---
# Resource Quota for Development namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: development-quota
  namespace: agnews-development
spec:
  hard:
    requests.cpu: "20"
    requests.memory: "40Gi"
    limits.cpu: "40"
    limits.memory: "80Gi"
    persistentvolumeclaims: "3"
    services.loadbalancers: "0"
    services.nodeports: "5"

---
# LimitRange for Production namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: production-limits
  namespace: agnews-production
spec:
  limits:
  - type: Container
    default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
  - type: PersistentVolumeClaim
    min:
      storage: "1Gi"
    max:
      storage: "100Gi"

---
# LimitRange for Staging namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: staging-limits
  namespace: agnews-staging
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
  - type: PersistentVolumeClaim
    min:
      storage: "1Gi"
    max:
      storage: "50Gi"

---
# LimitRange for Development namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: development-limits
  namespace: agnews-development
spec:
  limits:
  - type: Container
    default:
      cpu: "200m"
      memory: "512Mi"
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
    max:
      cpu: "1"
      memory: "2Gi"
    min:
      cpu: "10m"
      memory: "32Mi"
  - type: PersistentVolumeClaim
    min:
      storage: "1Gi"
    max:
      storage: "20Gi"
