# gRPC API Configuration for AG News Text Classification
# ================================================================================
# This configuration file defines settings for the gRPC API server including
# server options, service configurations, interceptors, and TLS settings.
#
# References:
#   - gRPC Documentation: https://grpc.io/docs/
#   - gRPC Performance Best Practices: https://grpc.io/docs/guides/performance/
#
# Author: Võ Hải Dũng
# License: MIT

# Server Configuration
server:
  # Network settings
  host: "0.0.0.0"
  port: 50051
  
  # Server options
  options:
    # Maximum number of concurrent RPCs this server will service
    max_concurrent_rpcs: 100
    
    # Maximum number of concurrent connections
    max_connection_idle_ms: 120000
    max_connection_age_ms: 600000
    max_connection_age_grace_ms: 10000
    
    # Message size limits (in bytes)
    max_receive_message_length: 10485760  # 10MB
    max_send_message_length: 10485760     # 10MB
    
    # Keepalive settings
    keepalive_time_ms: 120000
    keepalive_timeout_ms: 20000
    keepalive_permit_without_calls: false
    http2_min_recv_ping_interval_without_data_ms: 30000
    
  # Thread pool configuration
  thread_pool:
    max_workers: 10
    thread_name_prefix: "grpc-worker"
    
  # Compression settings
  compression:
    default_algorithm: "gzip"
    enabled_algorithms:
      - "gzip"
      - "deflate"
    
# Service-specific configurations
services:
  classification:
    enabled: true
    timeout_ms: 30000
    max_batch_size: 100
    cache_enabled: true
    cache_ttl_seconds: 300
    
  training:
    enabled: true
    timeout_ms: 3600000  # 1 hour for training operations
    max_concurrent_jobs: 5
    
  model_management:
    enabled: true
    timeout_ms: 60000
    max_model_size_mb: 1000
    
  data_service:
    enabled: true
    timeout_ms: 120000
    max_upload_size_mb: 100
    
  health:
    enabled: true
    check_interval_seconds: 30
    
  monitoring:
    enabled: true
    metrics_interval_seconds: 60

# Interceptor Configuration
interceptors:
  # Authentication interceptor
  auth:
    enabled: true
    jwt_secret_key: "${JWT_SECRET_KEY}"
    jwt_algorithm: "HS256"
    token_expiry_seconds: 3600
    exclude_methods:
      - "/agnews.health.v1.HealthService/Check"
      - "/agnews.health.v1.HealthService/Watch"
    
  # Logging interceptor
  logging:
    enabled: true
    log_level: "INFO"
    log_request_body: false
    log_response_body: false
    exclude_methods:
      - "/agnews.health.v1.HealthService/Check"
    
  # Metrics interceptor
  metrics:
    enabled: true
    histogram_buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
    
  # Error handling interceptor
  error:
    enabled: true
    include_stack_trace: false
    sanitize_errors: true
    
  # Rate limiting interceptor
  rate_limit:
    enabled: true
    default_rate: 100
    default_burst: 200
    per_method_limits:
      "/agnews.classification.v1.ClassificationService/Classify": 
        rate: 1000
        burst: 2000
      "/agnews.classification.v1.ClassificationService/ClassifyBatch":
        rate: 100
        burst: 200
      "/agnews.training.v1.TrainingService/StartTraining":
        rate: 10
        burst: 20

# TLS Configuration
tls:
  enabled: false
  cert_file: "/path/to/server.crt"
  key_file: "/path/to/server.key"
  ca_file: "/path/to/ca.crt"
  client_auth_required: false
  
# Reflection Configuration
reflection:
  enabled: true  # Enable for development, disable in production
  
# Health Check Configuration
health_check:
  service_name: "agnews-grpc-api"
  check_dependencies: true
  dependencies:
    - name: "database"
      type: "postgresql"
      critical: true
    - name: "redis"
      type: "redis"
      critical: false
    - name: "model_server"
      type: "http"
      critical: true
      
# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"
  
  tracing:
    enabled: true
    provider: "jaeger"
    sampling_rate: 0.1
    jaeger:
      agent_host: "localhost"
      agent_port: 6831
      
# Circuit Breaker Configuration
circuit_breaker:
  enabled: true
  failure_threshold: 5
  recovery_timeout_seconds: 60
  expected_error_rate: 0.1
