# REST API Configuration
# ================================================================================
# Configuration for FastAPI REST API server including server settings,
# middleware configuration, and operational parameters.
#
# References:
#   - FastAPI Configuration Best Practices
#   - The Twelve-Factor App: III. Config
#
# Author: Võ Hải Dũng
# License: MIT

# API Metadata
api:
  title: "AG News Text Classification API"
  version: "1.0.0"
  description: "Production-grade REST API for AG News text classification"
  terms_of_service: "https://api.agnews.ai/terms"
  contact:
    name: "AG News API Support"
    email: "support@agnews.ai"
    url: "https://api.agnews.ai/support"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  workers: 4  # Number of worker processes
  reload: false  # Auto-reload on code changes (dev only)
  log_level: "info"  # Logging level: debug, info, warning, error, critical
  access_log: true  # Enable access logging
  use_colors: true  # Colored logs
  proxy_headers: true  # Trust proxy headers
  forwarded_allow_ips: "*"  # IPs to trust for proxy headers
  
  # Timeout settings (seconds)
  timeout:
    keep_alive: 5
    request: 60
    response: 60
    
  # Request limits
  limits:
    max_request_size: 10485760  # 10MB
    max_upload_size: 524288000  # 500MB
    max_connections: 1000
    max_pending_connections: 100

# CORS Configuration
cors:
  enabled: true
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "https://app.agnews.ai"
    - "https://staging.agnews.ai"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "HEAD"
    - "PATCH"
  allowed_headers:
    - "*"
  exposed_headers:
    - "X-Total-Count"
    - "X-RateLimit-Limit"
    - "X-RateLimit-Remaining"
    - "X-RateLimit-Reset"
    - "X-Request-ID"
  allow_credentials: true
  max_age: 3600  # Preflight cache duration

# Rate Limiting Configuration
rate_limit:
  enabled: true
  strategy: "token_bucket"  # token_bucket, sliding_window, distributed, adaptive
  
  # Default limits
  requests_per_second: null
  requests_per_minute: 60
  requests_per_hour: 1000
  requests_per_day: 10000
  burst_size: 10
  
  # Redis configuration for distributed rate limiting
  redis_url: "${REDIS_URL:redis://localhost:6379/0}"
  
  # Adaptive rate limiting
  enable_adaptive: false
  adaptive_config:
    min_factor: 0.1
    max_factor: 2.0
    cpu_threshold: 80
    memory_threshold: 85
    error_rate_threshold: 0.05
    
  # Custom limits by endpoint
  endpoint_limits:
    "/api/v1/classify":
      requests_per_minute: 100
      burst_size: 20
    "/api/v1/classify/batch":
      requests_per_minute: 30
      burst_size: 5
    "/api/v1/training/start":
      requests_per_minute: 5
      burst_size: 2
      
  # Custom limits by user role
  role_limits:
    admin:
      requests_per_minute: 1000
      requests_per_hour: 10000
    service:
      requests_per_minute: 500
      requests_per_hour: 5000
    user:
      requests_per_minute: 60
      requests_per_hour: 1000
    guest:
      requests_per_minute: 20
      requests_per_hour: 100

# Middleware Configuration
middleware:
  # Security middleware
  security:
    enabled: true
    csrf_protection: false  # Disabled for API
    xss_protection: true
    content_type_validation: true
    max_content_length: 10485760  # 10MB
    trusted_hosts:
      - "api.agnews.ai"
      - "*.agnews.ai"
      - "localhost"
    security_headers:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      Referrer-Policy: "strict-origin-when-cross-origin"
      
  # Logging middleware
  logging:
    enabled: true
    log_request_body: false  # Log request bodies (careful with sensitive data)
    log_response_body: false  # Log response bodies
    max_body_length: 1000  # Max body length to log
    exclude_paths:
      - "/health"
      - "/metrics"
      - "/docs"
      - "/openapi.json"
    sensitive_fields:
      - "password"
      - "token"
      - "api_key"
      - "secret"
      - "authorization"
      
  # Metrics middleware
  metrics:
    enabled: true
    detailed_metrics: true
    exclude_paths:
      - "/metrics"
      - "/health"
    buckets:  # Latency histogram buckets (seconds)
      - 0.01
      - 0.025
      - 0.05
      - 0.1
      - 0.25
      - 0.5
      - 1.0
      - 2.5
      - 5.0
      - 10.0
      
  # Compression middleware
  compression:
    enabled: true
    minimum_size: 1000  # Minimum response size to compress
    level: 6  # Compression level (1-9)
    
  # Request ID middleware
  request_id:
    enabled: true
    header_name: "X-Request-ID"
    generate_if_missing: true
    
  # Timeout middleware
  timeout:
    enabled: true
    default_timeout: 60  # seconds
    endpoint_timeouts:
      "/api/v1/training/start": 300
      "/api/v1/data/upload": 300

# API Documentation
documentation:
  enabled: true  # Enable in development
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"
  title: "AG News API Documentation"
  swagger_ui_oauth2_redirect_url: "/docs/oauth2-redirect"
  swagger_ui_init_oauth: null
  swagger_ui_parameters:
    docExpansion: "none"
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    filter: true
    showExtensions: true
    showCommonExtensions: true

# Validation Configuration
validation:
  strict_mode: true  # Strict validation mode
  allow_extra_fields: false  # Allow extra fields in requests
  max_text_length: 10000  # Maximum text length for classification
  max_batch_size: 100  # Maximum batch size
  max_dataset_size: 524288000  # 500MB
  
  # Text validation
  text:
    min_length: 1
    max_length: 10000
    min_words: 1
    max_words: 2000
    allowed_languages:
      - "en"
      
  # Model validation
  models:
    allowed:
      - "deberta-v3-large"
      - "roberta-large"
      - "xlnet-large"
      - "electra-large"
      - "longformer-large"
      - "ensemble"
      - "default"
      
  # Training validation
  training:
    min_epochs: 1
    max_epochs: 100
    min_batch_size: 1
    max_batch_size: 256
    min_learning_rate: 0.0000001
    max_learning_rate: 0.01

# WebSocket Configuration
websocket:
  enabled: true
  path: "/ws"
  ping_interval: 30  # seconds
  ping_timeout: 10  # seconds
  max_connections: 1000
  max_message_size: 1048576  # 1MB
  
  # Subscription limits
  max_subscriptions_per_client: 10
  allowed_topics:
    - "predictions"
    - "training"
    - "models"
    - "system"

# Monitoring and Health Checks
monitoring:
  health_check_path: "/health"
  readiness_path: "/health/ready"
  liveness_path: "/health/live"
  startup_path: "/health/startup"
  metrics_path: "/metrics"
  
  # Health check thresholds
  thresholds:
    cpu_critical: 90
    cpu_warning: 70
    memory_critical: 90
    memory_warning: 80
    disk_critical: 95
    disk_warning: 85
    
  # Prometheus metrics
  prometheus:
    enabled: true
    path: "/metrics"
    include_in_schema: false

# Error Handling
error_handling:
  include_traceback: false  # Include traceback in error responses (dev only)
  max_error_message_length: 500
  log_errors: true
  
  # Error response format
  error_format: "problem_json"  # problem_json or simple
  
  # Custom error messages
  error_messages:
    400: "Bad Request - The request was invalid or cannot be served"
    401: "Unauthorized - Authentication credentials were missing or incorrect"
    403: "Forbidden - The request is understood, but access is refused"
    404: "Not Found - The requested resource could not be found"
    429: "Too Many Requests - Rate limit exceeded"
    500: "Internal Server Error - An error occurred processing the request"
    503: "Service Unavailable - The service is temporarily unavailable"

# Feature Flags
features:
  enable_batch_processing: true
  enable_streaming: true
  enable_training_api: true
  enable_model_management: true
  enable_data_upload: true
  enable_metrics_api: true
  enable_explanation_api: true
  enable_feedback_api: true
  enable_websocket: true
  enable_graphql: false
  enable_grpc: false
  
  # Experimental features
  experimental:
    enable_auto_scaling: false
    enable_distributed_training: false
    enable_model_versioning: true
    enable_a_b_testing: false

# Environment-specific overrides
environments:
  development:
    server:
      reload: true
      log_level: "debug"
    documentation:
      enabled: true
    error_handling:
      include_traceback: true
    middleware:
      logging:
        log_request_body: true
        log_response_body: true
        
  staging:
    server:
      workers: 2
      log_level: "info"
    documentation:
      enabled: true
      
  production:
    server:
      workers: 8
      log_level: "warning"
    documentation:
      enabled: false
    rate_limit:
      strategy: "distributed"
      enable_adaptive: true
