# Soft‑voting or stacking ensemble
ensemble:
  method: soft_voting      # options: soft_voting, stacking
  weights:
    deberta: 0.5
    longformer: 0.5
  stacking_model_path: outputs/checkpoints/stacking_model.joblib
  class_names:
    - World
    - Sports
    - Business
    - Sci/Tech

inference:
  batch_size: 8
  max_len: 512
  stride: 256
