name: Lint & Static Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint, Format & Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==23.1.0 isort==5.12.0 flake8==6.0.0 mypy==1.5.1

      - name: Black check
        run: |
          black --check --diff .

      - name: isort check
        run: |
          isort --check-only --diff .

      - name: Flake8 lint
        run: |
          # enforce code style, catch unused imports, undefined names
          flake8 src tests --max-line-length=88 --extend-ignore=E203,W503

      - name: MyPy static type check
        run: |
          mypy src --ignore-missing-imports --show-error-codes

      - name: Report success
        run: echo "Lint, format, and type checks passed!"
